### ISSUE TITLE
Released Docker Image has Incompatible JDK

### ISSUE THREAD

**Issue by RMichaelSwan** [nasa/VICAR#2]
VOS 3.0's centos7_for_vos_installed.img.gz contains a docker Centos7 image with VOS and JRE 1.7. A number of libraries in VICAR require JRE 1.8, e.g. java jpl.mipl.io.jConvertIIO. Perhaps someone could upload an updated docker image? It's a bit jarring to get everything up only for the assumed good container not to contain a notable dependency.

**Comment by wbunch42** [comment]
Thanks! We'll look into it.

**Comment by wbunch42** [comment]
This has been corrected. The new *_2.img.gz at https://github.com/nasa/VICAR/releases now have Java 1.8 installed. Thanks for the catch.
